#!/bin/bash

set -e

PS_BLOAT=-1mil
PS_FADE=0.25
ASSY_SCALE=1.5

pcb -x png --outfile ${1%.pcb}.png --dpi 600 --photo-mode --photo-plating copper --photo-mask-colour purple $1
#pcb -x png --outfile ${1%.pcb}_bot.png --dpi 600 --photo-mode --photo-flip-x --photo-plating copper --photo-mask-colour purple $1
pcb -x ps --psfile ${1%.pcb}.ps --ps-bloat $PS_BLOAT --align-marks --outline --auto-mirror --media A5 --drill-copper --show-legend $1
pcb -x ps --psfile ${1%.pcb}_mirror.ps --ps-bloat $PS_BLOAT --align-marks --outline --mirror --auto-mirror --media A5 --drill-copper --show-legend $1
pcb -x ps --psfile ${1%.pcb}_inv.ps --ps-bloat $PS_BLOAT --align-marks --outline --mirror --auto-mirror --ps-invert --media A5 --no-drill-copper --show-legend $1
pcb -x ps --psfile ${1%.pcb}_scaled.ps --ps-bloat $PS_BLOAT --psfade $PS_FADE --scale $ASSY_SCALE --align-marks --outline --auto-mirror --media A4 --drill-copper --show-legend $1

psselect 2 ${1%.pcb}_inv.ps ${1%.pcb}_top.ps
psselect 3 ${1%.pcb}_inv.ps ${1%.pcb}_bot.ps
psselect _1 ${1%.pcb}.ps ${1%.pcb}_fab.ps
psselect -p_3 -p_2 ${1%.pcb}_scaled.ps ${1%.pcb}_assy.ps
psselect -p_5 -p_4 ${1%.pcb}_mirror.ps ${1%.pcb}_paste.ps

gs -o ${1%.pcb}.pdf -sDEVICE=pdfwrite -sPAPERSIZE=a5 -dFIXEDMEDIA -dCompatibilityLevel=1.4 ${1%.pcb}_top.ps ${1%.pcb}_bot.ps ${1%.pcb}_paste.ps ${1%.pcb}_fab.ps
gs -o ${1%.pcb}_assy.pdf -sDEVICE=pdfwrite -sPAPERSIZE=a4 -dPDFFitPage -dCompatibilityLevel=1.4 ${1%.pcb}_assy.ps

rm ${1%.pcb}_mirror.ps ${1%.pcb}_inv.ps ${1%.pcb}_scaled.ps ${1%.pcb}_top.ps ${1%.pcb}_bot.ps ${1%.pcb}_fab.ps ${1%.pcb}_assy.ps ${1%.pcb}_paste.ps
